FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\Shot.bf", "src\\Player.bf", "src\\Entity.bf", "src\\GameApp.bf", "src\\Timer.bf", "src\\Transform.bf", "src\\Images.bf", "src\\Sprite.bf"]

[MainWindow]
X = 1346
Y = 397
Width = 1200
Height = 1024
ShowKind = "Normal"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 200.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Timer.bf"
TabWidth = 87.0
Type = "SourceViewPanel"
FilePath = "src\\Timer.bf"
CursorPos = 482
ProjectName = "Asteroids Tutor"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "GameApp.bf"
TabWidth = 103.0
Type = "SourceViewPanel"
FilePath = "src\\GameApp.bf"
CursorPos = 1125
ProjectName = "Asteroids Tutor"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Player.bf"
TabWidth = 79.0
Type = "SourceViewPanel"
FilePath = "src\\Player.bf"
CursorPos = 898
VertPos = 540.0
ProjectName = "Asteroids Tutor"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Shot.bf"
TabWidth = 81.0
Type = "SourceViewPanel"
FilePath = "src\\Shot.bf"
CursorPos = 576
VertPos = 216.0
ProjectName = "Asteroids Tutor"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Sprite.bf"
TabWidth = 79.0
Type = "SourceViewPanel"
FilePath = "src\\Sprite.bf"
CursorPos = 142
ProjectName = "Asteroids Tutor"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Entity.bf"
TabWidth = 76.0
Type = "SourceViewPanel"
FilePath = "src\\Entity.bf"
CursorPos = 1462
VertPos = 702.0
ProjectName = "Asteroids Tutor"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Transform.bf"
TabWidth = 104.0
Type = "SourceViewPanel"
FilePath = "src\\Transform.bf"
CursorPos = 149
VertPos = 54.0
ProjectName = "Asteroids Tutor"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Images.bf"
TabWidth = 87.0
Type = "SourceViewPanel"
FilePath = "src\\Images.bf"
CursorPos = 659
VertPos = 108.0
ProjectName = "Asteroids Tutor"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 121.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1471.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 77.0
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1471.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
Type = "OutputPanel"

[[Breakpoints]]
File = "src\\Player.bf"
Line = 55
Column = 6

[[Breakpoints]]
File = "src\\Shot.bf"
Line = 44
Column = 3
